baseURL = 'http://JB-électricité.fr/'
languageCode = 'en-us'
title = 'JB-électricité'
theme = 'up-business-theme'
favicon = "images/JB.svg" 
enableRobotsTXT = true

[languages]
[languages.en]
description = "Electricien entre Dole & Besançon (25)"
languageName ="French"

# Weight used for sorting.
weight = 1

############################## navigation ###############################

[[menu.main]]
  name = 'A propos'
  pageRef = '/post/A_propos'
  weight = 10


#################### default parameters ################################

[params]
# Repository configuration (URLs for in-page links to opening issues and suggesting changes)
github_repo = "https://github.com/GANitak/JB-Electricite/issues"

#Google Custom Search Engine ID. Remove or comment out to disable search.
gcs_engine_id = ""

# Enable Algolia DocSearch
algolia_docsearch = false

# Enable Lunr.js offline search
offlineSearch = false

# Enable syntax highlighting and copy buttons on code blocks with Prism
prism_syntax_highlighting = false

# defaultTheme: light
defaultTheme = "dark"
#defaultTheme: auto # to switch between dark or light according to browser theme

# Useful when translating.
enableMissingTranslationPlaceholders = true
############################# social site ########################

[[params.social]]
icon = "fab fa-github"
link = "https://github.com/GANitak"

# You can add your own taxonomies
[taxonomies]
tag = "tags"
category = "categories"

[params.taxonomy]
# set taxonomyCloud = [] to hide taxonomy clouds
taxonomyCloud = ["tags", "categories"]

# If used, must have same length as taxonomyCloud
taxonomyCloudTitle = ["Tag Cloud", "Categories"]

# set taxonomyPageHeader = [] to hide taxonomies on the page headers
taxonomyPageHeader = ["tags", "categories"]

# Image processing configuration.
[imaging]
resampleFilter = "CatmullRom"
quality = 75
anchor = "smart"